### ISSUE TITLE
Crash on "Import from external storage"

### ISSUE THREAD

**Issue by dougszumski** [cowboy-coders/CyclismoProject#21]
03-19 20:07:37.486  18012-18058/org.cowboycoders.cyclisimo E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #5
    Process: org.cowboycoders.cyclisimo, PID: 18012
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalArgumentException: A track must have an owner
            at org.cowboycoders.cyclisimo.content.MyTracksProviderUtilsImpl.validateTrack(MyTracksProviderUtilsImpl.java:446)
            at org.cowboycoders.cyclisimo.content.MyTracksProviderUtilsImpl.insertTrack(MyTracksProviderUtilsImpl.java:452)
            at org.cowboycoders.cyclisimo.io.file.GpxImporter.onTrackElementStart(GpxImporter.java:271)
            at org.cowboycoders.cyclisimo.io.file.GpxImporter.startElement(GpxImporter.java:211)
            at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143)
            at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method)
            at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513)
            at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
            at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
            at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
            at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
            at javax.xml.parsers.SAXParser.parse(SAXParser.java:187)
            at org.cowboycoders.cyclisimo.io.file.GpxImporter.importGPXFile(GpxImporter.java:159)
            at org.cowboycoders.cyclisimo.ImportAsyncTask.importFile(ImportAsyncTask.java:194)
            at org.cowboycoders.cyclisimo.ImportAsyncTask.doInBackground(ImportAsyncTask.java:155)
            at org.cowboycoders.cyclisimo.ImportAsyncTask.doInBackground(ImportAsyncTask.java:63)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by cowboy-coders** [comment]
Fixed in feature/mapsforge.
